# Generated by Django 3.0.3 on 2020-06-10 04:48

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='著者名')),
                ('description', models.TextField(blank=True, verbose_name='備考')),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='ジャンル名')),
                ('description', models.TextField(verbose_name='備考')),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='タイトル')),
                ('date', models.DateTimeField(default=datetime.datetime(2020, 6, 10, 4, 48, 31, 709649, tzinfo=utc), verbose_name='読了日')),
                ('recommended', models.IntegerField(blank=True, verbose_name='おすすめ度')),
                ('comment', models.TextField(blank=True, verbose_name='コメント')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='books', to='records.Author', verbose_name='著者')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='books', to='records.Genre', verbose_name='ジャンル')),
            ],
        ),
    ]
