# Generated by Django 3.0.3 on 2020-06-10 05:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0002_auto_20200610_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='books', to='records.Author', verbose_name='著者'),
        ),
        migrations.AlterField(
            model_name='book',
            name='date',
            field=models.DateField(blank=True, verbose_name='読了日'),
        ),
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='books', to='records.Genre', verbose_name='ジャンル'),
        ),
        migrations.AlterField(
            model_name='genre',
            name='description',
            field=models.TextField(blank=True, verbose_name='備考'),
        ),
    ]
