# Generated by Django 3.0.3 on 2020-06-10 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0004_auto_20200610_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='recommended',
            field=models.IntegerField(choices=[(5, '5: とてもオススメ'), (4, '4: オススメ'), (3, '3: 普通'), (2, '2: どうだろう'), (1, '1: オススメせず')], verbose_name='おすすめ度'),
        ),
    ]
