# Generated by Django 3.0.3 on 2020-06-10 13:22

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0005_auto_20200610_2001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='books', to='records.Author', verbose_name='著者'),
        ),
        migrations.AlterField(
            model_name='book',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime.today, verbose_name='読了日'),
        ),
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='books', to='records.Genre', verbose_name='ジャンル'),
        ),
        migrations.AlterField(
            model_name='book',
            name='recommended',
            field=models.IntegerField(choices=[(5, '5: とてもオススメ'), (4, '4: オススメ'), (3, '3: 普通'), (2, '2: どうだろう'), (1, '1: オススメせず')], default=3, verbose_name='おすすめ度'),
        ),
    ]
